### PR TITLE
Ft comment resources

### PR DESCRIPTION
**Pull request by andela-oojewale**

### CODE REVIEW

**Comment by andela-oakinniranye** [comment]
Nice one @andela-oojewale! I think this is ok, but you may want to work on handling the chained methods e.g `resource.find_by(id: resource_id).comments` if the resource is not found, you would be chaining `comments` to `nil`, which would still return the exception you tried to escape. It's ok, but you may need to refactor after the merge :+1:

**Comment by andela-oojewale** [comment]
@andela-ooranagwa, that is handled with the rescue block in the method body. Moreover, it's been changed to `find_by` for sometime. You might want to `compare` the branch with master if you don't the latest state is not revealed in the PR thread you're seeing.

**Comment by andela-oakinniranye** [comment]
:+1: Saw these yesterday

**Comment by andela-oakinniranye** [comment]
:+1:

**Comment by andela-ooranagwa** [comment]
:+1:

**Pull request merged**
